title: "Orgelverein am Braunschweiger Dom e.V."
baseUrl: "https://www.orgel-braunschweigerdom.de/"
languageCode: "de"

metaDataFormat: "yaml"
defaultContentLanguage: "de"
summaryLength: 40
enableRobotsTXT: true
paginate: 5
paginatePath: "" # Append page number to list path directly.
disableKinds:
- taxonomies
- taxonomyTerm

sitemap:
  changeFreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

theme:
- hugo-video
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

params:
  env: production