title: "Orgelverein am Braunschweiger Dom e.V."
baseUrl: "https://www.orgel-braunschweigerdom.de/"
languageCode: "de"

metaDataFormat: "yaml"
defaultContentLanguage: "de"
enableRobotsTXT: true
paginate: 5
paginatePath: "" # Append page number to list path directly.
disableKinds:
  - taxonomies
  - taxonomyTerm

sitemap:
  changeFreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

params:
  env: production