name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v1
      - name: "🧰 Install Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.59.1
          extended: true
      - name: "🧰 Install Node"
        uses: actions/setup-node@v1
        with:
          node-version: 8.16.x
      - name: "🧰 Install Yarn"
        run: npm install -g yarn
      - name: "🧰 Install asset dependencies"
        run: |
          cd assets
          yarn install
      - name: "🏗 Build"
        run: hugo
